     AS COMMANDER OF THE UNITED STARSHIP ENTERPRISE,
YOUR MISSION IS TO RID THE GALAXY OF THE DEADLY
KLINGON MENACE.  TO DO THIS, YOU MUST DESTROY THE

YOU HAVE 40 SOLAR DAYS TO COMPLETE YOUR MISSION.

     YOU HAVE AT LEAST ONE SUPPORTING STARBASE.
WHEN THE ENTERPRISE DOCKS AT ONE (IS POSITIONED
NEXT TO ONE) IT IS RESUPPLIED WITH ENERGY AND
PHOTON TORPEDOES.  THE ENTERPRISE IS CURRENTLY IN

     THE GALAXY IS DIVIDED INTO 64 QUADRANTS WITH
THE FOLLOWING COORDINATES:
  1   2   3   4   5   6   7   8
---------------------------------
:   :   :   :   :   :   :   :   :  1
---------------------------------
:   :   :   :   :   :   :   :   :  2
---------------------------------
:   :   :   :   :   :   :   :   :  3
---------------------------------
:   :   :   :   :   :   :   :   :  4
---------------------------------
:   :   :   :   :   :   :   :   :  5
---------------------------------
:   :   :   :   :   :   :   :   :  6
---------------------------------
:   :   :   :   :   :   :   :   :  7
---------------------------------
:   :   :   :   :   :   :   :   :  8
---------------------------------
EACH QUADRANT IS SIMILARLY DIVIDED INTO 64 SECTORS.

::: DEVICES :::

WARP ENGINES:

COURSE = A REAL NUMBER IN DEGREES
NUMBERS INDICATE DIRECTION STARTING AT THE TOP AND
GOING CLOCKWISE.

       0
   315    45
        /
 270---*---90
      /
   225   135
      180

WARP FACTOR = A REAL NUMBER FROM 0 TO 8.
DISTANCE TRAVELED = INTEGER (WARP FACTOR) QUADRANTS:
  WARP .2 = THE ENTERPRISE TRAVELS 1 SECTOR.
       .5 =                        4 SECTORS.
        1 =                        1 QUADRANT.
        2 =                        2 QUADRANTS.


FOR EXAMPLE, IF YOU TRAVEL FROM:
QUADRANT 1 - 1, SECTOR 1 - 1, IN THE DIRECTION OF 90 DEGREES
AT WARP 2 YOU WOULD STOP AT QUADRANT 1 - 3, SECTOR 1 - 1
IN THE NEXT STARDATE.

*** NOTE:  EVERY USE OF THE WARP ENGINES TAKES ONE
STARDATE.  IF THE ENTERPRISE IS BLOCKED BY SOMETHING
DURING INTRA-QUADRANT TRAVEL IT WILL STOP IN FRONT
OF IT (AND WASTE A STARDATE) ***


SHORT RANGE SENSORS:

     THE SHORT RANGE SENSORS OF THE ENTERPRISE DISPLAY
A DETAILED VIEW OF THE QUADRANT IT IS CURRENTLY IN.
THE ENTERPRISE LOOKS LIKE "E" ON THE SCREEN.
KLINGON BATTLE CRUISERS LOOK LIKE "K" ON THE SCREEN.
STARBASES LOOK LIKE "B" AND STARS LOOK LIKE "*".

LONG RANGE SENSORS:

     THE LONG RANGE SENSORS OF THE ENTERPRISE DISPLAY
THE NUMBER OF OBJECTS IN THE 9 CLOSEST QUADRANTS.
EACH DIGIT OF THE NUMBER IN EACH BOX MEANS SOMETHING:
     THE ONES DIGIT REPRESENTS THE NUMBER OF STARS.
         TENS                                STARBASES.
         HUNDREDS                            KLINGONS.
FOR EXAMPLE:
319 MEANS 3 KLINGONS, 1 STARBASE AND 9 STARS.

PHASERS:

     ANY PORTION OF THE ENERGY AVAILABLE CAN BE FIRED.
THE BATTLE COMPUTER DIVIDES THIS AMOUNT AMONG THE
KLINGON CRUISERS IN THE QUADRANT AND DETERMINES
THE VARIOUS DIRECTIONS OF FIRE.  THE EFFECTIVENESS
OF A HIT DEPENDS MOSTLY ON THE DISTANCE TO THE
TARGET.  A KLINGON BATTLE CRUISER STARTS WITH 300
UNITS OF ENERGY.  IT CAN FIRE AN AMOUNT EQUAL TO
WHATEVER ENERGY IT HAS LEFT.

PHOTON TORPEDOES:

     INITIALLY THE ENTERPRISE HAS 10 PHOTON TORPEDOES.
ONE TORPEDO DESTROYS WHATEVER IT HITS.  THE RANGE
OF PHOTON TORPEDOES (LIKE PHASERS) IS LIMITED TO
THE CURRENT QUADRANT.  THE COURSE OF A PHOTON TORPEDO
IS SET THE SAME WAY AS THAT OF THE ENTERPRISE.

DAMAGE CONTROL REPORT:

THE DAMAGE CONTROL REPORT LISTS THE MAIN DEVICES AND
THEIR STATE OF REPAIR.   A NEGATIVE STATE OF REPAIR
INDICATES A DISABLED DEVICE.  DEVICES CAN BE DAMAGED OR
REPAIRED BY A SPACE STORM OR TRUCE, RESPECTIVELY.
ALSO, DAMAGED DEVICES ARE REPAIRED 1 UNIT EVERY STARDATE.



